# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSums <- function(mat) {
    .Call('_pkgS5_colSums', PACKAGE = 'pkgS5', mat)
}

getRndMt <- function() {
    .Call('_pkgS5_getRndMt', PACKAGE = 'pkgS5')
}

rcpparma_outerproduct <- function(x) {
    .Call('_pkgS5_rcpparma_outerproduct', PACKAGE = 'pkgS5', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_pkgS5_rcpparma_innerproduct', PACKAGE = 'pkgS5', x)
}

#' @export
callFunction <- function(x, f) {
    .Call('_pkgS5_callFunction', PACKAGE = 'pkgS5', x, f)
}

myfun <- function(X, Y) {
    .Call('_pkgS5_myfun', PACKAGE = 'pkgS5', X, Y)
}

getEigenValues <- function(X) {
    .Call('_pkgS5_getEigenValues', PACKAGE = 'pkgS5', X)
}

getMaxCpp <- function(v) {
    .Call('_pkgS5_getMaxCpp', PACKAGE = 'pkgS5', v)
}

cumsum1 <- function(x) {
    .Call('_pkgS5_cumsum1', PACKAGE = 'pkgS5', x)
}

cumsum2 <- function(x) {
    .Call('_pkgS5_cumsum2', PACKAGE = 'pkgS5', x)
}

cumsum_sug <- function(x) {
    .Call('_pkgS5_cumsum_sug', PACKAGE = 'pkgS5', x)
}

timesTwo <- function(x) {
    .Call('_pkgS5_timesTwo', PACKAGE = 'pkgS5', x)
}

positives <- function(x) {
    .Call('_pkgS5_positives', PACKAGE = 'pkgS5', x)
}

first_three <- function(x) {
    .Call('_pkgS5_first_three', PACKAGE = 'pkgS5', x)
}

with_names <- function(x, y) {
    .Call('_pkgS5_with_names', PACKAGE = 'pkgS5', x, y)
}

colSumsCpp <- function(mat) {
    .Call('_pkgS5_colSumsCpp', PACKAGE = 'pkgS5', mat)
}

